### ISSUE TITLE
Data readiness

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD2A-adapter#1]
https://www.ek9.org/index.php?threads/honda-usefull-ecu-pinouts-obd2b-obd2a-obd1.201/

**Comment by rusefillc** [comment]
https://www.hondacivicforum.com/forum/mechanical-problems-technical-chat-8/obd2a-obd2b-conversion-harness-questions-78677/

![image](https://user-images.githubusercontent.com/48498823/135078816-81261939-0d2a-4bc9-b3ed-e9355b088da9.png)

**Comment by rusefillc** [comment]
connector footprint pushed into repo, please init schematics files

**Comment by Qwerty-OFF** [comment]
Done

**Comment by rusefillc** [comment]
@Timbelom now it's your turn :)

**Comment by rusefillc** [comment]
@Timbelom maybe simpler to use https://github.com/rusefi/rusefi/wiki/Honda-Civic-1996

**Comment by rusefillc** [comment]
@Timbelom not available

@Qwerty-OFF please proceed with data entry
