### ISSUE TITLE
jumpers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD2A-adapter#11]
All used pins on C plugs let's have jumpers

![image](https://user-images.githubusercontent.com/48498823/139861475-ae03b601-0e4e-46c6-880a-3be5da6e3ba9.png)

All used not injectors A plugs let's have jumpers

![image](https://user-images.githubusercontent.com/48498823/139861529-c45820a9-8da7-4021-a595-b6157f231411.png)

**Comment by Qwerty-OFF** [comment]
Done
