### ISSUE TITLE
trigger signals

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD2A-adapter#4]
Wiring harness has 4 sensors. We would use two

TDC simple - we never use it
CYP would require vr-descrete module, that one is impossible to handle by MAX992x on Proteus due to MAX992x 85ms watchdog
CKP should be wired into Proteus by default. We also need jumpers allowing to wire crankshaft speed fluctuation. 

Open Q if we simply wire crankshaft speed fluctuation to Proteus second VR?

![Honda OBD2 mess](https://user-images.githubusercontent.com/48498823/138120004-354bd3e3-d93a-4e5d-8cf7-892871a8343c.png)

**Comment by rusefillc** [comment]
@mck1117 what Proteus output can control VR-discrete bias?

@mck1117 do we want to route VR-discrete analog into any of Proteus analog inputs? Which one?

**Comment by mck1117** [comment]
"crankshaft speed fluctuation sensor" this looks like hall effect -> digital input

**Comment by mck1117** [comment]
Not really analog inputs that can handle the analog output on Proteus directly.

As for PWM threshold: You can use IGN 5, as that's on PC7, which supports hardware PWM.  The challenge is that will output a 5v PWM signal, when the module expects a 3.3v PWM signal...

**Comment by rusefillc** [comment]
Perfect! @Qwerty-OFF can you do logic level transition from 5v into 3.3v on IGN 5 on PC7 for threshold?

For analog looks like it's just a test via for now :(

**Comment by Qwerty-OFF** [comment]
@mck1117 why we need a voltage translator? I see that the threshold generator is powered by 5V. Will 5V use require unwanted changes to PWM settings?

**Comment by mck1117** [comment]
Not the end of the world to make the change in software, but yes, that's why it would need to be different.  The hardware inside the VR module expects a 0-3.3v signal.  5v PWM wouldn't hurt it or anything, we'd just have to compensate in software.

**Comment by Qwerty-OFF** [comment]
Connected to IGN5 through jumper
