### ISSUE TITLE
Align pin usage with default pinout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD2A-adapter#5]
injector 1 please use LS1

See
three YAML files at https://github.com/rusefi/rusefi/tree/master/firmware/config/boards/proteus/connectors

see https://rusefi.com/docs/pinouts/proteus/ online tool

**Comment by rusefillc** [comment]
TODO: mention IAT/CLT on https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/proteus/connectors/white35.yaml

**Comment by rusefillc** [comment]
@Qwerty-OFF progress https://github.com/rusefi/rusefi/commit/582b3fdd070949913bc6d56489fe1d4ff7b28efa

**Comment by Qwerty-OFF** [comment]
Added notes
![image](https://user-images.githubusercontent.com/4116383/139138047-29f1cd9c-b797-4911-9e76-9d131795d551.png)
![image](https://user-images.githubusercontent.com/4116383/139138078-5d07c211-4421-4c22-8eed-67885c92f7c6.png)

**Comment by Qwerty-OFF** [comment]
Please close if ok
