### ISSUE TITLE
clarify A20 ignition

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD2A-adapter#6]
low side? high side? do we invert in HW or do we invert in SW?

**Comment by rusefillc** [comment]
@blundar @mck1117 asking for help that's the only open question for https://docs.google.com/spreadsheets/d/1NOu2Atvwz7war0sTAcp2MZZhsYdLY6VmwkuC-S1-yEU right now

**Comment by mck1117** [comment]
External pullup? Oh, that's easy! Use a lowside output.  External pullup pulls up (to fire), lowside driver pulls low (to charge) when MCU outputs logical high. No inversion required!

**Comment by Qwerty-OFF** [comment]
Used LS9 with 1k pullup
