### ISSUE TITLE
Confirm pin C6

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD2A-adapter#7]

**Comment by Qwerty-OFF** [comment]
Also A13, A14

**Comment by rusefillc** [comment]
https://docs.google.com/spreadsheets/d/1NOu2Atvwz7war0sTAcp2MZZhsYdLY6VmwkuC-S1-yEU

![image](https://user-images.githubusercontent.com/48498823/139499212-f59a22fb-3142-4258-b644-1d2e9955c9e4.png)

![image](https://user-images.githubusercontent.com/48498823/139499312-4dae09d7-1b50-49ed-9122-5ea5295531e2.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF we should have notes what did we come up with, I do not remember now :(

**Comment by Qwerty-OFF** [comment]
We figured out the purpose of the pins
