### ISSUE TITLE
inverted pins as comment on symbol

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD2A-adapter#9]
please add "inv 12" for "A1"
"INV 1" for A12

smaller font or less black grey or something to indicate secondary natute

**Comment by Qwerty-OFF** [comment]
A12 or A24 should be "inv 1"? If we want to use right angle connectors sometimes, it is necessary to place pin 1 of this connector in position A24.

**Comment by rusefillc** [comment]
let's forget about right angle connector for now. A12 would be "inv 1" that's the way current plastic 35 pin flips, right?

**Comment by Qwerty-OFF** [comment]
Can now be installed in two positions.  Make it install in only one way?

**Comment by rusefillc** [comment]
Absolutely please limit because i made mistake already. Only latches out

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/139560214-86964898-434d-400c-9782-93d01b0f6d9b.png)

**Comment by Qwerty-OFF** [comment]
Please close if ok
